version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:30'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'direct'
    labels:
      - 'dependencies'
      - 'automerge'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:30'
    open-pull-requests-limit: 3
    labels:
      - 'dependencies'
      - 'automerge'
