version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-all:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "automerge"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    groups:
      npm-all:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "automerge"
