name: Bug Report
description: Report a bug or issue with one of the tools
title: "[BUG] <tool-name>: Brief description of the bug"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: dropdown
    id: tool-name
    attributes:
      label: Tool Name
      description: Which tool is experiencing the bug?
      options:
        - Age Calculator
        - Area Calculator
        - BMI Calculator
        - Currency Converter
        - DOB Calculator
        - EMI Calculator
        - Goal Tracker
        - GST Calculator
        - Image Tools
        - Invoice Generator
        - Password Generator
        - Percentage Calculator
        - Prompt Generator
        - QR Code Generator
        - Timezone Converter
        - Tip Calculator
        - Todo List
        - Unit Converter
        - Timers Tools
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug in detail. What did you expect to happen? What actually happened?
      placeholder: |
        1. Go to [tool page]
        2. Enter [input values]
        3. Click [action]
        4. Expected: [expected result]
        5. Actual: [actual result]
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug
      placeholder: |
        1. Navigate to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen when following the reproduction steps?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens when following the reproduction steps?
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using? (e.g., Chrome 91.0.4472.124)
      placeholder: "e.g., Chrome 91.0.4472.124"

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, console errors, etc.)
      placeholder: |
        - Screenshots
        - Console errors
        - Network logs
        - Any other relevant information
