name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] Brief description of the requested feature"
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make ToolifyLab better for everyone.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Tool/Calculator
        - Enhancement to existing tool
        - UI/UX improvement
        - Performance improvement
        - Accessibility improvement
        - Mobile/PWA enhancement
        - API enhancement
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What's currently missing or difficult?
      placeholder: "Describe the problem this feature would address..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Describe how you think this feature should work:

        - How would users access this feature?
        - What would the user interface look like?
        - What inputs/outputs would be involved?
        - Any specific requirements or constraints?
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "List any alternative approaches you've thought about..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that would help understand your request
      placeholder: |
        - Screenshots from similar tools
        - Links to examples
        - Use cases or scenarios
        - Any research or data supporting this request
