name: Code Quality - Lint & Type Check

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    name: Code Quality - Lint & Type Check
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint with ESLint + ReviewDog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'

      - name: Type Check (TypeScript)
        run: npx tsc --noEmit
