name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci


      - name: Build Application
        run: npm run build

      - name: Generate Changelog
        id: changelog
        run: |
          # Get the previous tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREVIOUS_TAG" ]; then
            echo "No previous tag found, generating full changelog"
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            echo "Generating changelog from $PREVIOUS_TAG"
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges $PREVIOUS_TAG..HEAD)
          fi

          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name || inputs.version }}
          release_name: Release ${{ github.ref_name || inputs.version }}
          body: |
            ## 🚀 What's New

            ${{ steps.changelog.outputs.changelog }}

            ## 📦 Installation

            ```bash
            npm install toolifylab@${{ github.ref_name || inputs.version }}
            ```

            ## 🔗 Links

            - [Live Demo](https://tools.praveensingh.online)
            - [Documentation](https://github.com/Praveenskg/smart-tools#readme)
            - [Report Issues](https://github.com/Praveenskg/smart-tools/issues)

            ## 📊 Build Info

            - **Node.js:** 22
            - **Build Time:** $(date -u)
            - **Commit:** ${{ github.sha }}
          draft: false
          prerelease: ${{ contains(github.ref_name || inputs.version, 'beta') || contains(github.ref_name || inputs.version, 'alpha') }}

      - name: Upload Build Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .next/
          asset_name: build-${{ github.ref_name || inputs.version }}.tar.gz
          asset_content_type: application/gzip

  notify:
    runs-on: ubuntu-latest
    name: Notify Release
    needs: release
    if: always()

    steps:
      - name: Notify Success
        if: needs.release.result == 'success'
        run: |
          echo "✅ Release ${{ github.ref_name || inputs.version }} created successfully!"
          echo "🔗 Check it out at: https://github.com/Praveenskg/smart-tools/releases/tag/${{ github.ref_name || inputs.version }}"

      - name: Notify Failure
        if: needs.release.result == 'failure'
        run: |
          echo "❌ Release ${{ github.ref_name || inputs.version }} failed!"
          echo "Please check the logs for more details."
